[[language]]
name = "markdown"
language-server = { command = "marksman", args=["server"] }
file-types = ["md", "markdown", "PULLREQ_EDITMSG"]
scope = "source.md"
roots = [".marksman.toml"]
indent = { tab-width = 2, unit = " " }
injection-regex = "md|markdown"

[[language]]
name = "rust"
auto-format = true

[language-server.rust-analyzer.config.check]
command = "clippy"
