[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
language-server = { command = "marksman", args=["server"] }
file-types = ["md", "markdown", "PULLREQ_EDITMSG"]
scope = "source.md"
roots = [".marksman.toml"]
indent = { tab-width = 2, unit = " " }
injection-regex = "md|markdown"
