format = '''
  ┌─╼$username╾─╼$os╾─╼$time
  └─╼$directory$rust
  $character
'''
add_newline = true

[username]
format = '\[[$user@pop_os!](#d08770)\]'
disabled = false
show_always = true

[time]
disabled = false
format = '\[[$time](#5e81ac)\]'
time_format = '%r %v'

[directory]
format = '\[[$path](#8fbcbb)[$read_only]($read_only_style)\]'
read_only = " "
truncation_length = 5

[character]
format = '$symbol '
success_symbol = '[▶](#a3be8c)'
error_symbol = '[▶](#bf616a)'

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os]
disabled = false
format = '\[[$symbol](#ebcb8b)\]'

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = "  "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
symbol = " "

[python]
symbol = " "

[rust]
format = '\[[$symbol($version)]($style)\]'
symbol = " "